[package]
name = "onagre-launcher-bin"
version = "1.2.1"
edition = "2018"
license = "GPL-3.0-only"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
onagre-launcher-toolkit = { path = "../toolkit" }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", default-features = false, features = ["std", "fmt", "env-filter"] }
dirs = "4.0.0"
mimalloc = "0.1.30"

[dependencies.tokio]
version = "1.21.2"
features = ["rt"]
