[package]
name = "onagre-launcher"
version = "1.2.3"
license = "MPL-2.0"
authors = ["Michael Aaron Murphy <mmstick@pm.me>"]
description = "Library for writing plugins and frontends for pop-launcher"
repository = "https://github.com/pop-os/launcher"
edition = "2018"

[workspace]
members = ["bin", "plugins", "service", "toolkit"]

[dependencies]
const_format = "0.2.30"
dirs = "4.0.0"
futures = "0.3.25"
serde = { version = "1.0.147", features = ["derive"] }
serde_json = "1.0.87"
serde_with = "2.0.1"

[profile.release]
lto = true
panic = "abort"
strip = true

[dependencies.tokio]
version = "1.21.2"
features = ["io-std", "io-util"]

[dependencies.tokio-stream]
version = "0.1.11"
features = ["io-util"]
